### ISSUE TITLE
The sample OBJ file is missing from the project

### ISSUE THREAD

**Issue by daniel-packard** [patrickabadi/UrhoCustomObj#1]
The sample OBJ file is probably missing because the .gitignore excludes *.obj files

error message:
`'Could not find a part of the path 'C:\projects\UrhoCustomObj\UrhoCustomObj\UrhoCustomObj\Meshes\Model.obj'`

Thanks for sharing the code! Way better than wrestling with conversion of assets into MDL format at runtime 💯

**Comment by patrickabadi** [comment]
Fixed in latest.  Thanks @daniel-packard
